### ISSUE TITLE
Where did I use this wrong?

### ISSUE THREAD

**Issue by zhuhean** [pedant/sweet-alert-dialog#13]
java.lang.RuntimeException: Unknown animation name: cn.pedant.SweetAlert.Rotate3dAnimation error:cn.pedant.SweetAlert.Rotate3dAnimation
            at com.zhuhean.dongxi.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:77)
            at com.zhuhean.dongxi.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:64)
            at com.zhuhean.dongxi.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:41)
            at com.zhuhean.dongxi.SweetAlert.OptAnimationLoader.loadAnimation(OptAnimationLoader.java:22)
            at com.zhuhean.dongxi.SweetAlert.SweetAlertDialog.<init>(SweetAlertDialog.java:74)
            at com.zhuhean.dongxi.SweetAlert.SweetAlertDialog.<init>(SweetAlertDialog.java:66)
            at com.zhuhean.dongxi.settings.UserSettings$2.onPreferenceClick(UserSettings.java:32)
            at android.preference.Preference.performClick(Preference.java:1011)
            at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:222)
            at android.widget.AdapterView.performItemClick(AdapterView.java:298)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1288)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:2972)
            at android.widget.AbsListView$1.run(AbsListView.java:3767)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:153)
            at android.app.ActivityThread.main(ActivityThread.java:5326)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:848)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:615)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by pedant** [comment]
if you import the library source code into your project, please keep the src package structure. like 'cn.pedant.SweetAlert', not com.zhuhe.xxxx.SweetAlert'.
