### ISSUE TITLE
Crashing while rotating

### ISSUE THREAD

**Issue by danilodequeiroz** [pedant/sweet-alert-dialog#138]
My app crash when I try to rotate the device, follow the stacktrace:
 
` Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Button.startAnimation(android.view.animation.Animation)' on a null object reference
                                                                            at cn.pedant.SweetAlert.SweetAlertDialog.dismissWithAnimation(SweetAlertDialog.java:358)
                                                                            at cn.pedant.SweetAlert.SweetAlertDialog.dismissWithAnimation(SweetAlertDialog.java:353)
                                                                            at israelermel.zipimoveis.fragments.DetalheImovelFragment.showErrorMessage(DetalheImovelFragment.java:250)
                                                                            at israelermel.zipimoveis.fragments.DetalheImovelFragment.configDetalhe(DetalheImovelFragment.java:238)
                                                                            at israelermel.zipimoveis.fragments.DetalheImovelFragment.loadImovel(DetalheImovelFragment.java:143)
                                                                            at israelermel.zipimoveis.fragments.DetalheImovelFragment.onActivityCreated(DetalheImovelFragment.java:81)
                                                                            at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2201)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1326)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                            at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2900)
                                                                            at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
                                                                            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:603)
                                                                            at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
                                                                            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1265)
                                                                            at android.app.Activity.performStart(Activity.java:6915)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3216)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
                                                                            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5382) 
                                                                            at android.app.ActivityThread.access$1200(ActivityThread.java:221) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1800) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:158) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
`

**Comment by AnthonyNahas** [comment]
I am getting the same error too
