### ISSUE TITLE
Error in Dialog Box

### ISSUE THREAD

**Issue by spurts51** [pedant/sweet-alert-dialog#144]
I am using this in Canary 4 and it shows the following error and the application stops...

           Unknown animation name: cn.pedant.SweetAlert.Rotate3dAnimation error:null
                                                                  at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:77)
                                                                  at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:64)
                                                                  at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:41)
                                                                  at cn.pedant.SweetAlert.OptAnimationLoader.loadAnimation(OptAnimationLoader.java:22)
                                                                  at cn.pedant.SweetAlert.SweetAlertDialog.<init>(SweetAlertDialog.java:80)
                                                                  at com.dell.end.LoginActivity$5.onResponse(LoginActivity.java:213)
                                                                  at com.dell.end.LoginActivity$5.onResponse(LoginActivity.java:174)
                                                                  at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:60)
                                                                  at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:30)
                                                                  at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:7402)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by eakteam** [comment]
Same here...

**Comment by ghost** [comment]
It's because of Proguard for me. So, i add a exemption for the cn.pedant.SweetAlert.Rotate3dAnimation like this:

-keep class cn.pedant.SweetAlert.Rotate3dAnimation

on the proguard-rules.pro
