### ISSUE TITLE
FATAL EXCEPTION: main

### ISSUE THREAD

**Issue by parvendan** [pedant/sweet-alert-dialog#151]
Process: com.sample.edx, PID: 6955
                                                                  java.lang.RuntimeException: Unknown animation name: cn.pedant.SweetAlert.Rotate3dAnimation error:null
                                                                      at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:77)
                                                                      at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:64)
                                                                      at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:41)
                                                                      at cn.pedant.SweetAlert.OptAnimationLoader.loadAnimation(OptAnimationLoader.java:22)
                                                                      at cn.pedant.SweetAlert.SweetAlertDialog.<init>(SweetAlertDialog.java:80)
                                                                      at com.sample.edx.util.DialogFactory.progressDialog(DialogFactory.java:59)
                                                                      at com.sample.edx.ui.login.LoginActivity.loginCall(LoginActivity.java:145)
                                                                      at com.sample.edx.ui.login.LoginActivity.onClick(LoginActivity.java:74)
                                                                      at android.view.View.performClick(View.java:5637)
                                                                      at android.view.View$PerformClick.run(View.java:22429)
                                                                      at android.os.Handler.handleCallback(Handler.java:751)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by parvendan** [comment]
Added these in prograud 
 -keep class cn.pedant.SweetAlert.Rotate3dAnimation {
    public <init>(...);
 }
 -keep class cn.pedant.SweetAlert.** { *; }
  -keep class cn.pedant.SweetAlert.Rotate3dAnimation

**Comment by parvendan** [comment]
applicaiton build.gradel is  classpath 'com.android.tools.build:gradle:3.0.0-alpha9'
