### ISSUE TITLE
as3.0 gradle4.1闪退问题, 已解决.

### ISSUE THREAD

**Issue by Cazaea** [pedant/sweet-alert-dialog#159]
## 前言 ##

之前常用这个轮子, 近两年, 原作者不再维护, AS3.0引用报错, 在此声明新版使用方式.

### 通过我自己封装SweetAlertDialog添加依赖，直接引用 ###

参考项目地址:[https://github.com/Cazaea/SweetAlertDialog](https://github.com/Cazaea/SweetAlertDialog)

### 通过导入Library引用 ###

> 1.下载作者源码[https://github.com/pedant/sweet-alert-dialog](https://github.com/pedant/sweet-alert-dialog),将作者源码中library作为module引用; 
通过file-->new-->import Module(将作者源码中library直接导入)

>参考: [为项目添加Module依赖](http://blog.csdn.net/Wistorms/article/details/78412514)

>2.删除作者library-->build.gradle中给定的VERSION_NAME, GROUP,以及apply from引用, 更改版本信息(所有xxVersion值)与你的主包xxVersion值统一

    apply plugin: 'com.android.library'
	//version = VERSION_NAME
	//group = GROUP 
 		android {
    		compileSdkVersion 26
    		buildToolsVersion '26.0.2'

    		defaultConfig {
       			minSdkVersion 19
    		}

    		lintOptions {
        		abortOnError false
    		}
    	}

 		dependencies {
    		implementation 'com.pnikosis:materialish-progress:1.0'
 		}

	//apply from: 'https://raw.github.com/chrisbanes/gradle-mvn-push/master/gradle-mvn-push.gradle'

 ----------
>3.同上, 修改library-->src-->AndroidManifest文件中 xxVersion值与主包下值统一

	<?xml version="1.0" encoding="utf-8"?>
	<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    	xmlns:tools="http://schemas.android.com/tools"
    	package="cn.pedant.SweetAlert">

    	<application />

	</manifest>

 ----------
>4.顺便贴出主包信息, 仅供参考.

	apply plugin: 'com.android.application'

	android {
    	compileSdkVersion 26
    	buildToolsVersion '26.0.2'

    	defaultConfig {
    	    applicationId "cn.pedant.SweetAlert.sample"
    	    minSdkVersion 19
    	    targetSdkVersion 26
    	    versionCode 1
    	    versionName "1.0.0"
    	    testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
	
    	    multiDexEnabled true
    	    ndk {
    	        abiFilters "armeabi"
    	    }
    	}
	
    	lintOptions {
    	    abortOnError false
    	}
	
    	/*最新打包输出命名方式 com.xx.xx-versionName(versionCode).apk*/
    	applicationVariants.all { variant ->
    	    variant.outputs.all { output ->
    	        def newApkName = applicationId + "-" + variant.versionName + "(" + variant.versionCode + ")" + ".apk"
            	outputFileName = new File(newApkName)
        	}
    	}

	}

	dependencies {
    	implementation fileTree(include: ['*.jar'], dir: 'libs')
    	implementation 'com.android.support:appcompat-v7:26.1.0'
    	implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    	testImplementation 'junit:junit:4.12'
    	androidTestImplementation 'com.android.support.test:runner:1.0.1'
    	androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'

    	//compile 'cn.pedant.sweetalert:library:1.3'
    	implementation project(':library')
	}

**Comment by TraxexLoveDonut** [comment]
同样求解

**Comment by ydldtec** [comment]
求解

**Comment by ydldtec** [comment]
java.lang.RuntimeException: Unknown animation name: cn.pedant.SweetAlert.Rotate3dAnimation error:null
                                                                    at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:77)
                                                                    at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:64)
                                                                    at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:41)
                                                                    at cn.pedant.SweetAlert.OptAnimationLoader.loadAnimation(OptAnimationLoader.java:22)
                                                                    at cn.pedant.SweetAlert.SweetAlertDialog.<init>(SweetAlertDialog.java:80)
                                                                    at cn.pedant.SweetAlert.SweetAlertDialog.<init>(SweetAlertDialog.java:71)

**Comment by chshp1234** [comment]
闪退啦~~~

**Comment by GodManRui** [comment]
Android 3.0不行啦，同样的报错，求解~！我的好像是只有这个 SweetAlertDialog.PROGRESS_TYPE样式的报错

**Comment by yummyChina** [comment]
me too

**Comment by yummyChina** [comment]
你们都是mack出问题吗，我们这边windows没问题

**Comment by GodManRui** [comment]
我也是windows，跟操作系统没关系，是gradle升级到4.1之后出的问题。你windows没问题可能是没有升级gradle

**Comment by yummyChina** [comment]
android studio升级之后 会更改默认的jdk配置，改成自己的jdk目录试试看

**Comment by GodManRui** [comment]
那你改了么，管用么？ 我刚才已经花了一上午的时间把项目里所有用到这个框架的提示框全部替换了。。。其实感觉这个提示框有点浮夸，华而不实，老大一直想让我换，我一直懒得换。。

**Comment by yummyChina** [comment]
我是mack，还没找到更高目录的方式，windows好改的，我感觉改了就好了发自我的华为手机-------- 原始邮件 --------主题：Re: [pedant/sweet-alert-dialog] as3.0 gradle4.1闪退问题 (#159)发件人：GodRUI 收件人：pedant/sweet-alert-dialog 抄送：yummyChina <460669143@qq.com>,Comment 那你改了么，管用么？ 我刚才已经花了一上午的时间把项目里所有用到这个框架的提示框全部替换了。。。其实感觉这个提示框有点浮夸，华而不实，老大一直想让我换，我一直懒得换。。

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pedant/sweet-alert-dialog","title":"pedant/sweet-alert-dialog","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/pedant/sweet-alert-dialog"}},"updates":{"snippets":[{"icon":"PERSON","message":"@GodManRui in #159: 那你改了么，管用么？ 我刚才已经花了一上午的时间把项目里所有用到这个框架的提示框全部替换了。。。其实感觉这个提示框有点浮夸，华而不实，老大一直想让我换，我一直懒得换。。"}],"action":{"name":"View Issue","url":"https://github.com/pedant/sweet-alert-dialog/issues/159#issuecomment-340337227"}}}

**Comment by yummyChina** [comment]
话说有问题的都是jdk 1.8吗

**Comment by wufei-limit** [comment]
感觉新版的AS打包时有问题，library下的anim资源没有打包进去。我把这个库的源码down下来作为本地的module引入，运行没问题。

**Comment by yummyChina** [comment]
已解决 gradle.properties文件中加上android.enableAdapter2=false发自我的华为手机-------- 原始邮件 --------主题：Re: [pedant/sweet-alert-dialog] as3.0 gradle4.1闪退问题 (#159)发件人：jiaokang 收件人：pedant/sweet-alert-dialog 抄送：yummyChina <460669143@qq.com>,Comment 感觉新版的AS打包时有问题，library下的anim资源没有打包进去。我把这个库的源码down下来作为本地的module引入，运行没问题。

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pedant/sweet-alert-dialog","title":"pedant/sweet-alert-dialog","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/pedant/sweet-alert-dialog"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jiaokang in #159: 感觉新版的AS打包时有问题，library下的anim资源没有打包进去。我把这个库的源码down下来作为本地的module引入，运行没问题。"}],"action":{"name":"View Issue","url":"https://github.com/pedant/sweet-alert-dialog/issues/159#issuecomment-340388321"}}}

**Comment by wufei-limit** [comment]
能否告知下这项配置的意义，或者参考的文档？直接搜索android.enableAdapter2没搜索到资源。

**Comment by yummyChina** [comment]
只知道这个配合kotlin环境打包的，其他的也不清楚发自我的华为手机-------- 原始邮件 --------主题：Re: [pedant/sweet-alert-dialog] as3.0 gradle4.1闪退问题 (#159)发件人：jiaokang 收件人：pedant/sweet-alert-dialog 抄送：yummyChina <460669143@qq.com>,Comment 能否告知下这项配置的意义，或者参考的文档？直接搜索android.enableAdapter2没搜索到资源。

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pedant/sweet-alert-dialog","title":"pedant/sweet-alert-dialog","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/pedant/sweet-alert-dialog"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jiaokang in #159: 能否告知下这项配置的意义，或者参考的文档？直接搜索android.enableAdapter2没搜索到资源。"}],"action":{"name":"View Issue","url":"https://github.com/pedant/sweet-alert-dialog/issues/159#issuecomment-340396270"}}}

**Comment by Cazaea** [comment]
我已经解决这个问题:
1.下载作者源码,import library(将作者源码中library直接导入),
2.删除作者library-->build.gradle中给定的VERSION_NAME, GROUP,以及apply from引用, 更改版本信息(所有xxVersion值)与你的主包xxVersion值统一
`apply plugin: 'com.android.library'

//version = VERSION_NAME
//group = GROUP

android {
    compileSdkVersion 26
    buildToolsVersion '26.0.2'

    defaultConfig {
        minSdkVersion 19
    }

    lintOptions {
        abortOnError false
    }
    buildToolsVersion '26.0.2'
}

dependencies {
    implementation 'com.pnikosis:materialish-progress:1.0'
}

//apply from: 'https://raw.github.com/chrisbanes/gradle-mvn-push/master/gradle-mvn-push.gradle'`
3.同上, 修改library-->src-->AndroidManifest文件中 xxVersion值与主包下值统一
`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="cn.pedant.SweetAlert"
    android:versionCode="2"
    android:versionName="1.1">

    <uses-sdk
        android:minSdkVersion="19"
        android:targetSdkVersion="26" />

    <application />

</manifest>`
4.顺便贴出主包信息, 仅供参考, 如果各位还有什么问题, 希望能够一起交流
`apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion '26.0.2'

    defaultConfig {
        applicationId "cn.pedant.SweetAlert.sample"
        minSdkVersion 19
        targetSdkVersion 26
        versionCode 4
        versionName "2.0.1"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        multiDexEnabled true
        ndk {
            abiFilters "armeabi"
        }
    }

    lintOptions {
        abortOnError false
    }

    /*最新打包输出命名方式 com.xx.xx-versionName(versionCode).apk*/
    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            def newApkName = applicationId + "-" + variant.versionName + "(" + variant.versionCode + ")" + ".apk"
            outputFileName = new File(/*"${project.projectDir}/build/outputs/apk/" + variant.name,*/ newApkName)
        }
    }

}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    androidTestImplementation('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    androidTestImplementation 'junit:junit:4.12'

    //compile 'cn.pedant.sweetalert:library:1.3'
    implementation project(':library')
}
`

**Comment by GodManRui** [comment]
666.给大佬疯狂打call，虽然我已经从项目里删掉了。哈哈。厉害，这都能解决

**Comment by yummyChina** [comment]
这是我们组的技术达人搞定的。。。发自我的华为手机-------- 原始邮件 --------主题：Re: [pedant/sweet-alert-dialog] as3.0 gradle4.1闪退问题 (#159)发件人：GodRUI 收件人：pedant/sweet-alert-dialog 抄送：yummyChina <460669143@qq.com>,Comment 666.给大佬疯狂打call，虽然我已经从项目里删掉了。哈哈。厉害，这都能解决

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pedant/sweet-alert-dialog","title":"pedant/sweet-alert-dialog","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/pedant/sweet-alert-dialog"}},"updates":{"snippets":[{"icon":"PERSON","message":"@GodManRui in #159: 666.给大佬疯狂打call，虽然我已经从项目里删掉了。哈哈。厉害，这都能解决"}],"action":{"name":"View Issue","url":"https://github.com/pedant/sweet-alert-dialog/issues/159#issuecomment-340967801"}}}

**Comment by JokerHYC** [comment]
i solved this error by modify the source code
the mothod createAnimationFromXml from Class OptAnimationLoader
add } else if (name.equals("YOURPATH.Rotate3dAnimation")) {
anim = new Rotate3dAnimation(c, attrs);
}

**Comment by steven123151988** [comment]
android.enableAapt2=false    android.enableAapt2=false   android.enableAapt2=false   android.enableAapt2=false   android.enableAapt2=false   android.enableAapt2=false
@yummyChina

**Comment by steven123151988** [comment]
@

**Comment by miketrinh1995** [comment]
I found the solution. https://jitpack.io/p/Leogiroux/sweet-alert-dialog .

**Comment by Summer006** [comment]
以上两种方法我都试过了， import module可以用
I tried two ways above,  " import module" can work

1， https://jitpack.io/p/Leogiroux/sweet-alert-dialog .
    这个办法不靠谱，虽然最后可以运行了，但背景尺寸有问题，无故变大了很多，也没找到地方可以修改尺寸
   not good, background size changed, I cannot modify it 

2，import module
       这个方法没问题，可以用， 就是工程多了个依赖项目很不爽
      can work, so far so good. 
      not pleased with adding a dependency module :(
