### ISSUE TITLE
cn.pedant.SweetAlert.Rotate3dAnimation error:null --- Crashing

### ISSUE THREAD

**Issue by rahulrainaaa** [pedant/sweet-alert-dialog#162]
FATAL EXCEPTION: main
                                                                Process: com.app.gofoodie, PID: 4704
                                                                java.lang.RuntimeException: Unknown animation name: cn.pedant.SweetAlert.Rotate3dAnimation error:null
                                                                    at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:77)
                                                                    at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:64)
                                                                    at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:41)
                                                                    at cn.pedant.SweetAlert.OptAnimationLoader.loadAnimation(OptAnimationLoader.java:22)
                                                                    at cn.pedant.SweetAlert.SweetAlertDialog.<init>(SweetAlertDialog.java:80)
                                                                    at com.app.gofoodie.activity.derived.CartOrderActivity.menuProceed(CartOrderActivity.java:280)
                                                                    at com.app.gofoodie.activity.derived.CartOrderActivity.onOptionsItemSelected(CartOrderActivity.java:109)
                                                                    at android.app.Activity.onMenuItemSelected(Activity.java:3206)
                                                                    at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:360)
                                                                    at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:194)
                                                                    at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:110)
                                                                    at android.support.v7.app.AppCompatDelegateImplV9.onMenuItemSelected(AppCompatDelegateImplV9.java:676)
                                                                    at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:821)
                                                                    at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
                                                                    at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:968)
                                                                    at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
                                                                    at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:623)
                                                                    at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:147)
                                                                    at android.view.View.performClick(View.java:5675)
                                                                    at android.view.View$PerformClick.run(View.java:22646)
                                                                    at android.os.Handler.handleCallback(Handler.java:836)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                    at android.os.Looper.loop(Looper.java:203)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6251)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1075)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by RaminNikmanesh** [comment]
i have this error too

**Comment by msingh86** [comment]
use this  https://github.com/thomper/sweet-alert-dialog

**Comment by rahulrainaaa** [comment]
![capture](https://user-images.githubusercontent.com/14292123/32878684-1557fc1a-cacd-11e7-97a5-0726f968565b.PNG)

**Comment by lucianocheng** [comment]
BTW, for those still following this thread:

This is happening because it's failing to turn the `50%` string from `pivotX` / `pivotY` into the integer '50', which it needs.

It's failing on this line in `OptAnimationLoader.java`, specifically the call to `.newInstance(c, attrs);`

```
anim = (Animation) Class.forName(name).getConstructor(Context.class, AttributeSet.class).newInstance(c, attrs);
```

I forked the repo and changed `50%` to `50` and it worked.  This is the error I was seeing:

```
java.lang.RuntimeException: Unknown animation name: cn.pedant.SweetAlert.Rotate3dAnimation error:null
    at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:77)                      
    at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:64)
    at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:41)
    at cn.pedant.SweetAlert.OptAnimationLoader.loadAnimation(OptAnimationLoader.java:22)
```

For the record, this repo is unmaintained, and **everyone** should switch over to @thomper 's fork at [https://github.com/pedant/sweet-alert-dialog/](https://github.com/pedant/sweet-alert-dialog/) which works perfectly (thanks @thomper !!).

**Comment by sljjyy** [comment]
me too。。。。。。

**Comment by scdhao** [comment]
copy res/anim folder to project
edit error_frame_in.xml
remove Rotate3dAnimation

**Comment by imkobedroid** [comment]
Have I met the solution, too?

**Comment by ArslanKathia** [comment]
me too facing this issue..

**Comment by kkgowtham** [comment]
@scdhao It worked for me.
1)Copy the anim folder from library to your preoject in res folder.
2)Then remove this 
    

> <sweet:cn.pedant.SweetAlert.Rotate3dAnimation
>         sweet:rollType="x"
>         sweet:fromDeg="100"
>         sweet:toDeg="0"
>         sweet:pivotX="50%"
>         sweet:pivotY="50%"
>         android:duration="400"/>

from error_frame_in.xml

3)Rebuild the project and run..

**Comment by MuhammedAlmaz** [comment]
@kkgowtham thank you sir , its worked for me too.

**Comment by ashishnimrot** [comment]
java.lang.RuntimeException appears in Android Studio 3.X using Sweet Alert Dialog: Unknown animation name: cn.pedant.SweetAlert.Rotate3dAnimation error: null error

I read a lot of blogs on the Internet and said that using Sweet Alert Dialog has encountered similar problems. The solution is very strange. Some say that it is to download lib and import it into the project.

Some say it is a confusion problem, in fact, the solution is very simple, you can change the added dependency library.

Errored library, comment out

`implementation 'cn.pedant.sweetalert:library:1.3'
`

Add the following library

`implementation 'com.github.f0ris.sweetalert:library:1.5.1'
`

Ok run again, problem solving

**Comment by alirezaho2008** [comment]
just add this to proguard-rules.pro

```
 -keep class cn.pedant.SweetAlert.Rotate3dAnimation {
    public <init>(...);
 }
```

**Comment by Amol-B-Patil** [comment]
I got the solution! 
if you are using `implementation 'cn.pedant.sweetalert:library:1.3'` library, just add the below line in your `proguard-rules.pro` file.

`-keep class cn.pedant.** { *; }`

**Comment by rahulrainaaa** [comment]
> I got the solution!
> if you are using `implementation 'cn.pedant.sweetalert:library:1.3'` library, just add the below line in your `proguard-rules.pro` file.
> 
> `-keep class cn.pedant.** { *; }`

This one is working perfectly fine. Applying the above mentioned proguard rule in project.

**Comment by rpurnama1409** [comment]
> copy res/anim folder to project
> edit error_frame_in.xml
> remove Rotate3dAnimation

Solved this , thanks

**Comment by AustineGwa** [comment]
with already a working solution why can this not be added to the codebase of this library?

**Comment by thomper** [comment]
@AustineGwa the maintainer, @pedant has been missing in action for a long time.  I believe F0ris keeps his fork here up to date: https://github.com/F0RIS/sweet-alert-dialog

**Comment by AustineGwa** [comment]
@thomper Thanks will follow the other

**Comment by itsdani121** [comment]
> BTW, for those still following this thread:
> 
> This is happening because it's failing to turn the `50%` string from `pivotX` / `pivotY` into the integer '50', which it needs.
> 
> It's failing on this line in `OptAnimationLoader.java`, specifically the call to `.newInstance(c, attrs);`
> 
> ```
> anim = (Animation) Class.forName(name).getConstructor(Context.class, AttributeSet.class).newInstance(c, attrs);
> ```
> 
> I forked the repo and changed `50%` to `50` and it worked. This is the error I was seeing:
> 
> ```
> java.lang.RuntimeException: Unknown animation name: cn.pedant.SweetAlert.Rotate3dAnimation error:null
>     at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:77)                      
>     at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:64)
>     at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:41)
>     at cn.pedant.SweetAlert.OptAnimationLoader.loadAnimation(OptAnimationLoader.java:22)
> ```
> 
> For the record, this repo is unmaintained, and **everyone** should switch over to @thomper 's fork at https://github.com/pedant/sweet-alert-dialog/ which works perfectly (thanks @thomper !!).

how to move because in thompas git there is not implementation link
