### ISSUE TITLE
Run-time crash on API level 26

### ISSUE THREAD

**Issue by Rosharoon** [pedant/sweet-alert-dialog#164]
java.lang.RuntimeException: Unknown animation name: cn.pedant.SweetAlert.Rotate3dAnimation error:null
                                                                       at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:77)
                                                                       at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:64)
                                                                       at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:41)
                                                                       at cn.pedant.SweetAlert.OptAnimationLoader.loadAnimation(OptAnimationLoader.java:22)

**Comment by hatamiarash7** [comment]
try this : https://github.com/thomper/sweet-alert-dialog

**Comment by guicunha** [comment]
This project is deprecated?

**Comment by hatamiarash7** [comment]
yes
