### ISSUE TITLE
3D rotation issue with latest android studio version 3.0.0 and 3.0.1 

### ISSUE THREAD

**Issue by DeveloperAdam** [pedant/sweet-alert-dialog#165]
Hello buddy every one face the same issue do you resolve this issue or find any solution for this issue if yes then please give us answer here.

**Comment by VivekRai29** [comment]
##Same isssue with me..

 java.lang.RuntimeException: Unknown animation name: cn.pedant.SweetAlert.Rotate3dAnimation error:null
 at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:77)
at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:64)
at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:41)
at cn.pedant.SweetAlert.OptAnimationLoader.loadAnimation(OptAnimationLoader.java:22)
at cn.pedant.SweetAlert.SweetAlertDialog.<init>(SweetAlertDialog.java:80)

**Comment by Vel-San** [comment]
Same issue here.. i thought it was only me. Running latest version on Android Studio.

**Comment by sinadalvand** [comment]
i have same issue, please help

**Comment by dragonNLC** [comment]
i have same issue, please help

**Comment by ghost** [comment]
Not sure if this is a legal way of solving this, but i copied all the files from the library folder and placed them into the same folders on my project and placed the following code into erro_frame_in.xml animation file.

`<?xml version="1.0" encoding="utf-8"?>

<set xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/tools"
    android:interpolator="@android:anim/linear_interpolator"
    android:shareInterpolator="true">

    <alpha
        android:fromAlpha="0"
        android:toAlpha="1"
        android:duration="400"/>

    <app:com.lod.lod.utils.dialog.Rotate3dAnimation
        app:rollType="x"
        app:fromDeg="100"
        app:toDeg="0"
        app:pivotX="50%"
        app:pivotY="50%"
        android:duration="400"/>
</set>`

hope it helps :)

**Comment by heyulinxp** [comment]
I met the same problem too

**Comment by lucianocheng** [comment]
BTW, for those still following this thread:

This is happening because it's failing to turn the `50%` string from `pivotX` / `pivotY` into the integer '50', which it needs.

It's failing on this line in `OptAnimationLoader.java`, specifically the call to `.newInstance(c, attrs);`

```
anim = (Animation) Class.forName(name).getConstructor(Context.class, AttributeSet.class).newInstance(c, attrs);
```

I forked the repo and changed `50%` to `50` and it worked.  This is the error I was seeing:

```
java.lang.RuntimeException: Unknown animation name: cn.pedant.SweetAlert.Rotate3dAnimation error:null
    at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:77)                      
    at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:64)
    at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:41)
    at cn.pedant.SweetAlert.OptAnimationLoader.loadAnimation(OptAnimationLoader.java:22)
```

For the record, this repo is unmaintained, and **everyone** should switch over to @thomper 's fork at [https://github.com/pedant/sweet-alert-dialog/](https://github.com/pedant/sweet-alert-dialog/) which works perfectly (thanks @thomper !!).

**Comment by aamernabi** [comment]
Same issue here. Please fix this issue as soon as possible.

**Comment by vshnav51** [comment]
A workaround for now is to modify the gradle build version:

1. Go to build.gradle(Project: _PROJECTNAME_) and modify classpath as:
 classpath 'com.android.tools.build:gradle:2.3.3'
2. Go to build.gradle(Module: App) and modify buildtoolsversion as:
buildToolsVersion "25.0.2"
3. Sync.
4. Voila!

**Comment by xielihuang** [comment]
I solve this problem when i update my ide android studio android to 3.x and gradle plugin version is 4.1;
then , follow me , i tell u how to solve this problem;

first step:
download this sweetalert sources code, and copy library folder to anywhere;
second step:
in u project , create an new android library , copy the sources code into this library;
(java sources code and res folders souces) both them;
three step:
find build.gradle file in u download library, copy 'compile 'com.pnikosis:materialish-progress:1.0' into u library that u create;
four step:
add this library that u create into main module.  build and run ... u can find this problems has been sovled!!!

**Comment by Olimov-Umidbek** [comment]
If you have some problem this library in android studio 3.0.0 or higher, I suggest 
compile 'com.github.f0ris.sweetalert:library:1.5.1' library. Both libraries are same.

**Comment by amarnathreddy2039** [comment]
I am also suffered with 3D rotation issue after that i was used this library..Please use below link who are using above android studio 3.3.1
https://github.com/thomper/sweet-alert-dialog and change the gradle file base on your android studio gradle versions

apply plugin: 'com.android.library'

android {
    compileSdkVersion 28
    buildToolsVersion '28.0.3'

    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    lintOptions {
        abortOnError false
    }
}

dependencies {

    implementation 'com.pnikosis:materialish-progress:1.7'
}

remove 
//apply from: 'https://raw.github.com/chrisbanes/gradle-mvn-push/master/gradle-mvn-push.gradle'
