### ISSUE TITLE
Unknown animation name

### ISSUE THREAD

**Issue by Mateeen** [pedant/sweet-alert-dialog#184]
rocess: production.kado.lock, PID: 22429
    java.lang.RuntimeException: Unknown animation name: cn.pedant.SweetAlert.Rotate3dAnimation error:null
        at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:77)
        at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:64)
        at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:41)
        at cn.pedant.SweetAlert.OptAnimationLoader.loadAnimation(OptAnimationLoader.java:22)
        at cn.pedant.SweetAlert.SweetAlertDialog.<init>(SweetAlertDialog.java:80)
        at production.kado.lock.fragments.SelectLockTypeFragment.setupFingerprint(SelectLockTypeFragment.java:179)
        at production.kado.lock.fragments.SelectLockTypeFragment.onClick(SelectLockTypeFragment.java:156)
        at android.view.View.performClick(View.java:5217)
        at android.view.View$PerformClick.run(View.java:21342)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5551)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

why are you using reflection?

**Comment by Anandsoni14** [comment]
I also got same issue.

**Comment by HelloNick666** [comment]
I also got same issue.

**Comment by WilsonKifua** [comment]
Unknown animation name: cn.pedant.SweetAlert.Rotate3dAnimation error:null

**Comment by javyhoo** [comment]
Unknown animation name: cn.pedant.SweetAlert.Rotate3dAnimation error:null

**Comment by ellie-me** [comment]
same issue here :( trying to solve the problem at the moment

**Comment by leruyn** [comment]
you can fix in anim/error_frame_in.xml:
<app:<your_package>.Rotate3dAnimation
    app:rollType="x"
    app:fromDeg="100"
    app:toDeg="0"
    app:pivotX="50%"
    app:pivotY="50%"
    android:duration="400"/>

**Comment by fivedofficial** [comment]
#leruyn where to use this?

**Comment by rsneena** [comment]
I am also facing the same issue. Is there any solution for this? This issue occurs in release apk, and in debug apk its working fine. 

Fatal Exception: java.lang.RuntimeException
Unknown animation name: cn.pedant.SweetAlert.Rotate3dAnimation error:cn.pedant.SweetAlert.Rotate3dAnimation
cn.pedant.SweetAlert.OptAnimationLoader.loadAnimation
cn.pedant.SweetAlert.OptAnimationLoader.loadAnimation (Unknown Source)

This is the issue that i got from fabric crashlytics

**Comment by jmimohsin** [comment]
same issue.

**Comment by leruyn** [comment]
@nonoman62 you can fix it in anim/error_frame_in.xml

**Comment by cristianmgb** [comment]
implementation 'com.github.f0ris.sweetalert:library:1.5.1'  try this, is the same library

**Comment by superancun** [comment]
just do it
 -keep class cn.pedant.SweetAlert.Rotate3dAnimation {
      public \<init\>(...);
 }

**Comment by moonlight2012** [comment]
> implementation 'com.github.f0ris.sweetalert:library:1.5.1' try this, is the same library

good .

**Comment by Joinfeng** [comment]
> You can try:
> <app:<your_package>.Rotate3dAnimation
> app:rollType="x"
> app:fromDeg="100"
> app:toDeg="0"
> app:pivotX="50%"
> app:pivotY="50%"
> android:duration="400"/>

有用
