### ISSUE TITLE
Dialog Animation Issue

### ISSUE THREAD

**Issue by dadajigunjal** [pedant/sweet-alert-dialog#186]
Caused by: java.lang.RuntimeException: Unknown animation name: cn.pedant.SweetAlert.Rotate3dAnimation error:null
                                                                          at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:77)
                                                                          at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:64)
                                                                          at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:41)
                                                                          at cn.pedant.SweetAlert.OptAnimationLoader.loadAnimation(OptAnimationLoader.java:22)
                                                                          at cn.pedant.SweetAlert.SweetAlertDialog.<init>(SweetAlertDialog.java:80)
                                                                          at cn.pedant.SweetAlert.SweetAlertDialog.<init>(SweetAlertDialog.java:71)

**Comment by ellie-me** [comment]
Same issue here :/

**Comment by leruyn** [comment]
You can try:
<app:<your_package>.Rotate3dAnimation
    app:rollType="x"
    app:fromDeg="100"
    app:toDeg="0"
    app:pivotX="50%"
    app:pivotY="50%"
    android:duration="400"/>

hope it helps.

**Comment by dadajigunjal** [comment]
Actually this error while integrate using dependencies not on clone/download from git.
Dependancies is here : 
compile 'cn.pedant.sweetalert:library:1.3'

And 
repositories {
    mavenCentral()
}

**Comment by moonlight2012** [comment]
java.lang.RuntimeException: Unknown animation name: cn.pedant.SweetAlert.Rotate3dAnimation error:null

Same issue here

**Comment by Johnliu520** [comment]
sdk not work  ，beacuse using dependencies，U should clone/download from git，and import this as moudle
