### ISSUE TITLE
java.lang.NoSuchFieldError: cn.pedant.SweetAlert.R$id.title_text

### ISSUE THREAD

**Issue by Bharatchavan20** [pedant/sweet-alert-dialog#26]
I am using sweet dialog to show dialog on in my app
here is my code,
 SweetAlertDialog  pDialog = new SweetAlertDialog(mContext, SweetAlertDialog.PROGRESS_TYPE);
                    pDialog.getProgressHelper().setBarColor(Color.parseColor("#A5DC86"));
                    pDialog.setTitleText("Loading");
                    pDialog.setCancelable(false);
                    pDialog.show();

Got Runtime Error:
E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NoSuchFieldError: cn.pedant.SweetAlert.R$id.title_text
            at cn.pedant.SweetAlert.SweetAlertDialog.onCreate(SweetAlertDialog.java:143)
            at android.app.Dialog.dispatchOnCreate(Dialog.java:351)
            at android.app.Dialog.show(Dialog.java:256)
            at com.cloudvisionsystems.webapp.ShowWebView$1.onLoadResource(ShowWebView.java:98)
            at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:529)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4895)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:994)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by pedant** [comment]
try to recompile your project, ensure R.java including res indexs of the SweetAlertDialog library ..

**Comment by bmrbehnam** [comment]
i  have same error - how to fix it ?

**Comment by bmrbehnam** [comment]
my question in stackoverflow [in this link](https://stackoverflow.com/questions/59493879/android-sweetalert-error-no-field-title-text-of-type-i-in-class-lcn-pedant-swe)
