### ISSUE TITLE
i just compiled your project copy you sample code but this error showd....

### ISSUE THREAD

**Issue by JokerHYC** [pedant/sweet-alert-dialog#43]
java.lang.NoSuchFieldError: cn.pedant.SweetAlert.R$id.title_text

**Comment by abhimanyuraj** [comment]
Have you get any solution for this?

**Comment by 515459445** [comment]
遇到了同样的问题：
 java.lang.NoSuchFieldError: No field title_text of type I in class Lcn/pedant/SweetAlert/R$id; or its superclasses (declaration of 'cn.pedant.SweetAlert.R$id' appears in /data/app/com.sunlawyers.n.sunim-2/base.apk)
                                                                            at cn.pedant.SweetAlert.SweetAlertDialog.onCreate(SweetAlertDialog.java:143)
                                                                            at android.app.Dialog.dispatchOnCreate(Dialog.java:514)
                                                                            at android.app.Dialog.show(Dialog.java:380)
                                                                            at com.sunlawyers.n.sunim.views.MySweetAlertDialog.showDeleteAlertDialog(MySweetAlertDialog.java:146)
                                                                            at com.sunlawyers.n.sunim.homepage.approve.activity.ApplyDetailsActivity.cancelRemind(ApplyDetailsActivity.java:360)
                                                                            at com.sunlawyers.n.sunim.homepage.approve.activity.ApplyDetailsActivity.access$600(ApplyDetailsActivity.java:87)
                                                                            at com.sunlawyers.n.sunim.homepage.approve.activity.ApplyDetailsActivity$2.handleMessage(ApplyDetailsActivity.java:331)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:101)
                                                                            at android.os.Looper.loop(Looper.java:156)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6577)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
