### ISSUE TITLE
proguard error

### ISSUE THREAD

**Issue by JokerHYC** [pedant/sweet-alert-dialog#49]
java.lang.RuntimeException: Unknown animation name: cn.pedant.SweetAlert.Rotate3dAnimation error:<init> [class android.content.Context, interface android.util.AttributeSet]
            at cn.pedant.SweetAlert.OptAnimationLoader.a(OptAnimationLoader.java:77)
            at cn.pedant.SweetAlert.OptAnimationLoader.a(OptAnimationLoader.java:64)
            at cn.pedant.SweetAlert.OptAnimationLoader.a(OptAnimationLoader.java:41)
            at cn.pedant.SweetAlert.OptAnimationLoader.a(OptAnimationLoader.java:22)
            at cn.pedant.SweetAlert.SweetAlertDialog.<init>(SweetAlertDialog.java:80)

**Comment by snakemouse3d** [comment]
try to add this line to your proguard file:
-keep class cn.pedant.SweetAlert.*\* { *; }

**Comment by maobon** [comment]
same wrong?why??? use that demo build jar file, and copy all res file into my project, finally add that jar file. run!  java.lang.RuntimeException: Unknown animation name: cn.pedant.SweetAlert.Rotate3dAnimation error:

**Comment by JokerHYC** [comment]
i solved this error by modify the source code 
the mothod createAnimationFromXml from Class OptAnimationLoader
add  } else if (name.equals("YOURPATH.Rotate3dAnimation")) {
                anim = new Rotate3dAnimation(c, attrs);
            }
problem solved...

**Comment by maobon** [comment]
Thanks a lot! SweetAlert needs Materialish_progress, so I download another open source project. add them all...solved....

**Comment by Tesvia** [comment]
I've got the same issue.
I didn't understand if the solution is just to add the line
-keep class cn.pedant.SweetAlert.*\* { *; }
to the proguard file.
Can someone help?
Thanks

**Comment by RishabJaiswal** [comment]
Instead of adding the library as a dependency in gradle file.
1.  imported the library as a gradle module in my project, Rename it as 'sweetalert' or whatever u like.

2. then in mothod createAnimationFromXml of Class OptAnimationLoader
add else if (name.equals("Rotate3dAnimation")) {
anim = new Rotate3dAnimation(c, attrs);
} as told above by @JokerHYC 

3.include module dependency in app's module as compile project(':sweetalert')

Voila! That's it.

**Comment by sonwani237** [comment]
use it
 -keep class cn.pedant.SweetAlert.Rotate3dAnimation {
    public <init>(...);
}
