### ISSUE TITLE
NoClassDefFoundError 编译完不能打开demo..

### ISSUE THREAD

**Issue by EvilsoulM** [pedant/sweet-alert-dialog#5]
java.lang.NoClassDefFoundError: com.networkbench.agent.impl.background.NBSApplicationStateMonitor
            at cn.pedant.SweetAlert.sample.SampleActivity.onStart(SampleActivity.java)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
            at android.app.Activity.performStart(Activity.java:5304)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2171)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2259)
            at android.app.ActivityThread.access$800(ActivityThread.java:138)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5061)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:812)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by pedant** [comment]
com.networkbench.agent 这个类是哪儿来的， **不是demo代码**报错，网上查了下 nbs.newlens.agent (8) 
NetworkBench NewLens Android Agent SDK（北京基调网络系统有限公司透镜系统Android SDK 提供Android应用运行时性能监控服务）， 可能你设备上装了其他监控应用导致的启动失败吧！

**Comment by gzl003** [comment]
是你因为Android studio的缓存机制导致的 删除Users\user\.gradle\daemon 目录下的两个文件registry.bin  registry.bin.lock 就好了
windows 下的更简单换个工作空间就好了
全是听云个大坑比导致的
