### ISSUE TITLE
ProGuard Issue

### ISSUE THREAD

**Issue by mrfanatic** [pedant/sweet-alert-dialog#6]
java.lang.RuntimeException: Unknown animation name: cn.pedant.SweetAlert.Rotate3dAnimation error:cn.pedant.SweetAlert.Rotate3dAnimation
            at cn.pedant.SweetAlert.a.a(Unknown Source)
            at cn.pedant.SweetAlert.a.a(Unknown Source)
            at cn.pedant.SweetAlert.a.a(Unknown Source)
            at cn.pedant.SweetAlert.a.a(Unknown Source)
            at cn.pedant.SweetAlert.j.<init>(Unknown Source)
            at cn.pedant.SweetAlert.j.<init>(Unknown Source)
            at my.app.a.a(Unknown Source)
            at my.app.a.f.onClick(Unknown Source)
            at android.view.View.performClick(View.java:4443)
            at android.view.View$PerformClick.run(View.java:18433)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5021)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by mrfanatic** [comment]
currently i manage to bypass the error by adding this to proguard file:
-keep class cn.pedant.*\* { *; }

**Comment by pedant** [comment]
You should not keep all library class.Maybe you can add the configuration like following, that's enough!

```
-keep class cn.pedant.SweetAlert.Rotate3dAnimation {
  public <init>(...);
}
```

**Comment by alwancreation** [comment]
where this is config should be placed ?
-keep class cn.pedant.SweetAlert.Rotate3dAnimation {
  public <init>(...);
}
thanks

**Comment by lucianocheng** [comment]
@alwancreation it should go in your `app/proguard-rules.pro` file.

Also just a heads up: I hit this error as well, but it was unrelated to Proguard.  See https://github.com/pedant/sweet-alert-dialog/issues/148

**Comment by weiwenhuaming01** [comment]
@pedant   你可以在主页写一下

**Comment by monirehJoghataee** [comment]
-keep class cn.pedant.SweetAlert.Rotate3dAnimation {
public (...);
}
this not work for me :(

**Comment by yunusemrecetin** [comment]
You can use this;

`-keep class cn.pedant.SweetAlert.** { *; }`
