### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: android.view.WindowManager$BadTokenException

### ISSUE THREAD

**Issue by PongPloy2016** [pedant/sweet-alert-dialog#96]
com.luminos.sso.activity.RegisterActivity.sweetAlertDialogCheck catch in Fatal Exception: java.lang.RuntimeException: android.view.WindowManager$BadTokenException  in android verction 4.4.2 

cade i 

```
`SweetAlertDialog pDialog ;
                        pDialog = new SweetAlertDialog(RegisterActivity.this, SweetAlertDialog.WARNING_TYPE);
                        pDialog.setTitleText(getResources().getString(R.string.login_fail));
                        pDialog.setContentText(message);
                        pDialog.setConfirmText("OK");
                        pDialog.setConfirmClickListener(new SweetAlertDialog.OnSweetClickListener() {
                            @Override
                            public void onClick(SweetAlertDialog sDialog) {
                                sDialog.dismissWithAnimation();

                            }
                        });
                        pDialog.show();


                    }
                });`
```

catch Error 

```
Fatal Exception: java.lang.RuntimeException: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@42134a48 is not valid; is your activity running?
       at com.loopj.android.http.AsyncHttpResponseHandler.onUserException(AsyncHttpResponseHandler.java:304)
       at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:395)
       at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:510)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5017)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@42134a48 is not valid; is your activity running?
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:536)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:259)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
       at android.app.Dialog.show(Dialog.java:286)
       at com.luminos.sso.activity.RegisterActivity.sweetAlertDialogCheck(RegisterActivity.java:586)
       at com.luminos.sso.activity.RegisterActivity.access$900(RegisterActivity.java:65)
       at com.luminos.sso.activity.RegisterActivity$4.onFailure(RegisterActivity.java:518)
       at com.loopj.android.http.JsonHttpResponseHandler.onFailure(JsonHttpResponseHandler.java:233)
       at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:359)
       at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:510)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5017)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
       at dalvik.system.NativeStart.main(NativeStart.java)


```

**Comment by AndroConsis** [comment]
crashed into Same error. You got solution?

**Comment by Jboob** [comment]
三种解决办法：
1、Activity 的生命周期跟Dialog的生命周期的冲突，Activity 更换成Application;
2、try cache;
3、判断当前context是否可用，不可用return;

**Comment by Wamae** [comment]
Change context you are giving Alert to YOUR_ACTIVITY.this .It worked for me.
