### ISSUE TITLE
Rotate3dAnimation wrong

### ISSUE THREAD

**Issue by akbot88** [pedant/sweet-alert-dialog#97]
I configed the gradle and New a instance ,then show()
app crashed . error log are below .
p.s. import package declaration is surely cn.pedant.SweetAlert (Automatically imported by IDE)

07-27 17:51:00.000 30141-30141/com.creawor.tianwang E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.creawor.tianwang, PID: 30141
                                                                      java.lang.RuntimeException: Unknown animation name: com.creawor.tianwang.dialog.Rotate3dAnimation error:com.creawor.tianwang.dialog.Rotate3dAnimation
                                                                          at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:77)
                                                                          at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:64)
                                                                          at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:41)
                                                                          at cn.pedant.SweetAlert.OptAnimationLoader.loadAnimation(OptAnimationLoader.java:22)
                                                                          at cn.pedant.SweetAlert.SweetAlertDialog.<init>(SweetAlertDialog.java:80)
                                                                          at com.creawor.tianwang.login.LoginActivity.onClick(LoginActivity.java:113)
                                                                          at com.creawor.tianwang.login.LoginActivity$$ViewBinder$InnerUnbinder$1.doClick(LoginActivity$$ViewBinder.java:37)
                                                                          at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                                                                          at android.view.View.performClick(View.java:4444)
                                                                          at android.view.View$PerformClick.run(View.java:18457)
                                                                          at android.os.Handler.handleCallback(Handler.java:733)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:136)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5113)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by akbot88** [comment]
Problem Solved . I had an old anim.xml file which contain a namespace named com.creawor.tianwang.dialog.Rotate3dAnimation, this may be conflict .

in values/attr.xml resource also found a declare-styleable item whose name is Rotate3dAnimation make the conflict
